README.md

corrected minor spelling error in tippecanoe

spelling error in tippecanoe

---

README.md

Following products have been added :
* [LuciadRIA](http://www.luciad.com/solutions/luciadria) - A JavaScript library for 3D globes and maps, with support for military symbology and desktop-like performance
* [LuciadLightspeed](http://www.luciad.com/solutions/luciadlightspeed) - A Java library that provides the foundations for advanced geospatial analytics applications
* [LuciadFusion](http://www.luciad.com/solutions/luciadfusion) - An all-in-one server solution for your data publication workflow and geospatial data management

added LuciadRIA, LuciadLightspeed & LuciadFusion

---

README.md

This PR adds the TIN Terrain CLI tool.

Add TIN Terrain

---

README.md

Added the spatial database format Geopackage, which is like SQLite, but with lessons learned, more capabilities (rasters support etc), and all in all better and more modern. And it is an open standard developed by OGC.

Geopackage

---

README.md

Hi. I'm a creator of **[MaxRev.Gdal.Core](https://github.com/MaxRev-Dev/gdal.netcore)** package which provides bindings for **GDAL 3.0 and OGR** running on **NET Core** (both runtimes win-x64 and linux-x64).

add MaxRev.Gdal.Core

---

README.md

Large-scale WebGL-powered Geospatial Data Visualization By Ant Financial
https://github.com/antvis/L7

add L7 library

---

README.md

I hope you find this resource suitable for your list. I am the author of this library.

Add d3-geomap

---

README.md

Parse OpenStreetMap (OSM) XML and Overpass JSON/XML.

Add osm2geojson to Python section

---

README.md

Hi @sacridini, thanks for this awesome list. I think DEM Net deserves a slot under C Sharp. Thanks !

Add DEM Net Elevation API proposal

---

README.md

Add Ginkgoch as one of the JavaScript section

Add Ginkgoch as one of the JavaScript section

---

README.md

MovingPandas implements a Trajectory class and corresponding methods based on GeoPandas.

Add MovingPandas to the Python section

---

README.md

- Add pgRouting to database section
- Fix GeoNames & Natural Earth urls

Add pgRouting to database section & fix GeoNames & Natural Earth urls

---

README.md

Under **Web Map Server**, adds a link to the open source XYZ tile server Terracotta https://github.com/DHI-GRAS/terracotta

Add Web Map Server: Terracotta

---

README.md

Hey @sacridini 
just fixing a link.
Cheers!

Fixing eCognition link

---

README.md

https://eodag.readthedocs.io/en/latest/
Command line tool and a plugin-oriented Python framework for searching, aggregating results and downloading remote sensed images while offering a unified API for data access regardless of the data provider.

Add EODAG in the Python list

---

README.md

I ordered the entries within the categories of the readme alphabetically. The order of the categories did not change. No content was added or removed.
Feel free to reject if this is not what you had in mind.

Alphabetical ordering in Readme

---

README.md

Hey,
I'm adding my project `geotiff` to the python list. The project is still in its early stages, but I thought I'd create this PR to put it on your radar. 
The advantage of using this package is that it does not depend on GDAL, meaning you can install with only pip. 
I'm also looking to get feedback on UI and conventions before continuing with any serious development.

Add geotiff to Python list

---

README.md

They deserve a mention for being so useful.

Added `geopocuh` and `pouchdb-geospatial` under JavaScript

---

README.md

Remove duplicate GeoPandas

---

README.md

Included the pygeoapi. A nice dockerized tool to quickly deploy RESTful OGC API.

Included pygeoapi

---

README.md

Shameless plug, adding my podcast, [Minds Behind Maps](https://minds-behind-maps.simplecast.com/) :-)

Adding Minds Behind Maps podcast

---

README.md

I just found this repo and I want to contribute to it since I'm a Spatial Data Scientist.
Here a add a few podcasts, from ESRI to USGS.

Add new podcasts

---

README.md

From ESRI, Google, and other International relevant geospatial communities

Add conferences

---

README.md

Requesting to update the PySAL documentation and to update the repo for rust-shapefile.

Update PySAL docs; rust-shapefile repo

---

README.md

Please consider adding HyRiver that provides access to many geospatial web services.

Add HyRiver

---

README.md

Hi 👋 , 
i'd love for you to add this Tile38 database client to the list.

docs: add pyle38 tile38 client

---

README.md

And fixes minor typo for OpenLayers.

Adds Oskari Map Application Platform

---

README.md

Hello everyone,
we are creating a port of turf.js for the Dart programming language (therefore **Flutter** as well) and wanted to ask, if you want to add our library to your awesome list? 😄 
Thank you in advance
CC @armantorkzaban

Added turf_dart

---

README.md

https://github.com/banesullivan/localtileserver

Add localtileserver

---

README.md

add MerginMaps.com to the SaaS section

---

README.md

This and #105 (sorry for two pr's) catch my eye's on [observable](https://observablehq.com/community)'s community page. I've been checking weekly or biweekly for last 5-6 months!

added geoverview

---

README.md

I would like to add [yogrt](https://github.com/Anagraph/yogrt) to the database section

Add yogrt to database section

---

README.md

Hi Eduardo,
see issue #113.
Best,
Paul

Add python -> geoapify

---

README.md

Hi Eduardo, 
First of all, thank you for compiling and sharing all these resources. I have been following you repo for a while now. I decided to do my first contribution adding [ArcGIS Platform](https://developers.arcgis.com/documentation/glossary/arcgis-platform/) to the list. I wasn't sure which link to include, http://developers.arcgis.com could be the alternative.
I didn't see any contributing.md so I hope you find value on it.
Thanks!

Adding ArcGIS Platform (PaaS) for developers

---

README.md

Linq is a business process modeling tool and is irrelevant to GIS

Remove LINQ

---

README.md

alphabetized programming languages

---

README.md

These two packages have been renamed in the Julia programming language.

Reflect renaming of Raster handling tools in Julia

---

README.md

Added `awesome-spectral-indices` (Awesome Lists), `spectral` (Google Earth Engine), and `spyndex` (Python).

Added the Awesome Spectral Indices Suite

---

README.md

A web service for geospatial operations.

Merge request: add WebGISService. Geospatial operations running as a service

---

README.md

Fix URL and improve description.

Update GeoStats.jl entry

---

README.md

Added `cubo`: A Python package for easily creating EO mini cubes from STAC :rocket:

Added cubo

---

README.md

I've created a project that provides in-memory Geo-spatial Indexing, with 2-dimensional K-D Tree. I've worked on multiple projects where I used K-D Trees to find the nearest neighbors for provided geo coordinates with efficient results. Hence a generic implementation for all.
The project has already received a lot of love from geoheads from different parts of the world

Add geo-assist

---

README.md

Hey, a pull-request to add [EOmaps](https://github.com/raphaelquast/EOmaps) to the list of python-packages.
Thanks!

add EOmaps

---

README.md

Hey, I added [segment-geospatial](https://github.com/opengeos/segment-geospatial) to the list of deep learning.
Thanks to everyone for this amazing cumulative effort!

Added segment-geospatial repo to deep learning section

---

README.md

I think, listing [pyGMT](https://github.com/GenericMappingTools/pygmt) would be good :)

Added pyGMT

---

README.md

I added GNSS INS Post Processing Software. Those include post processing for kinetic systems like airborne gnss/ins systems as well as static gnss surveys/networks.

GNSS INS Software added

---

README.md

Hi there!
That's a great collection of geospatial software tools.
I would like to add SamGIS ([huggingface demo](https://huggingface.co/spaces/aletrn/samgis), [about page](https://trinca.tornidor.com/projects/samgis-segment-anything-applied-to-GIS)) to your list of geospatial software. My work can do machine learning-based (Segment Anything by Meta - Facebook), interactive image segmentation tasks applied to GIS and geo data.
Thank you and best regards, Alessandro

add: add SamGIS

---

README.md

Add pygeoif and fastkml to python libraries.
use https://github.com/sacridini/Awesome-Geospatial/pull/143/files?w=1 to ignore the whitespace changes

add pygeoif and fastkml

---

README.md

Updated the description of the ArcGIS API for JavaScript to "ArcGIS Maps SDK for JavaScript" and provided a more detailed explanation of its capabilities.

Update ArcGIS API for JavaScript to ArcGIS Maps SDK for JavaScript with enhanced description

---

README.md

Hey @sacridini  hope this one could be added! We'll be delivering more libraries soon :)

feat: add Urban Mapper

---

README.md

Hi @sacridini hope these packages could be added! Thanks!

Add urban-worm/streetscape/viewscape/dsmSearch

---

README.md

Added [city2graph](https://github.com/c2g-dev/city2graph) to the README.md in the section of Python!
Disclaimer: I am the maintainer of this package.

Add city2graph to README.md
